name: sample_dart_lib
description: A sample Dart library
version: 1.0.0
repository: https://github.com/cylixlee/sample-dart-lib
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
